### ISSUE TITLE
Cant get jest to run tests

### ISSUE THREAD

**Issue by mindsgn** [mindsgn/OrbytDapp#1]
Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/mindsgn/Projects/wallet/node_modules/react-native-gesture-handler/index.js:1
    export { default as Swipeable } from './Swipeable';
    ^^^^^^

    SyntaxError: Unexpected token export

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:988:58)
      at Object.<anonymous> (App.js:187:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.771s
Ran all test suites.
error Command failed with exit code 1.

**Comment by mindsgn** [comment]
testing issue fixed.
